apiVersion: skaffold/v2beta1
kind: Config
build:
  artifacts:
    #- image: frosty-web
    #  sync:
    #    manual:
    #      - src: '**/*.js'
    #        dest: '/usr/src/app'
    #  context: ./frosty-web/
    - image: frosty-api
      context: ./frosty-api/
    - image: frosty-mysql
      context: ./frosty-mysql/
deploy:
  kubeContext: docker-desktop
  kubectl:
    manifests:
      - ./loadbalancer.yaml
      #- ./frosty-web/kubernetes/*
      - ./frosty-api/kubernetes/*
      - ./frosty-mysql/kubernetes/*
