apiVersion: v1
kind: Service
metadata:
  name: frosty-web
  labels:
    app: frosty-web
spec:
  ports:
    - port: 80
      targetPort: web-port
      protocol: TCP
      name: http
  selector:
    app: frosty-web

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frosty-web
  labels:
    app: frosty-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frosty-web
  template:
    metadata:
      labels:
        app: frosty-web
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: frosty-web
          image: frosty-web
          ports:
            - name: web-port
              containerPort: 80
          livenessProbe:
            exec:
              command:
              - whoami
            initialDelaySeconds: 3
            periodSeconds: 3
