apiVersion: v1
kind: Service
metadata:
  name: frosty-api
  labels:
    app: frosty-api
spec:
  ports:
    - port: 80
      targetPort: api-port
      protocol: TCP
      name: http
  selector:
    app: frosty-api

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frosty-api
  labels:
    app: frosty-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frosty-api
  template:
    metadata:
      labels:
        app: frosty-api
    spec:
      terminationGracePeriodSeconds: 1 # ok for local dev
      containers:
        - name: frosty-api
          image: frosty-api
          env:
            - name: PORT
              value: "80"
            - name: MYSQL_HOST
              value: "frosty-mysql"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_DB
              value: "frosty"
          ports:
            - name: api-port
              containerPort: 80
          livenessProbe:
            exec:
              command:
              - whoami
            initialDelaySeconds: 3
            periodSeconds: 3
